using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Controls;

namespace P7SExtractor
{
    public partial class DonationWindow : Window
    {
        // We rely on usual InitializeComponent generated by WPF
        public DonationWindow()
        {
            InitializeComponent();
            ApplyLanguage();
        }

        private void ApplyLanguage()
        {
            lblTitle.Text = Localization.T("Susține aplicația", "Support the app");
            txtDescription.Text = Localization.T("Această aplicație este gratuită. Dacă îți este utilă, o poți susține printr-o donație.",
                "This application is free. If you find it useful, you can support it with a donation.");

            btnDonate.Content = Localization.T("Donează ❤️", "Donate ❤️");
            btnLater.Content = Localization.T("Mai târziu", "Later");
        }

        private void OpenLink(string url)
        {
            try
            {
                Process.Start(new ProcessStartInfo { FileName = url, UseShellExecute = true });
            }
            catch (Exception ex)
            {
                MessageBox.Show(this, ex.Message, "Error", MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }

        private void BtnDonate_Click(object sender, RoutedEventArgs e)
        {
            // Open fixed Revolut link
            OpenLink("https://revolut.me/alinuf62");
        }

        private void BtnLater_Click(object sender, RoutedEventArgs e)
        {
            // record that user dismissed todays prompt
            try
            {
                var settings = AppSettings.LoadSettings();
                settings.LastDonationPromptDate = DateTime.UtcNow.ToString("yyyy-MM-dd");
                settings.SaveSettings();
            }
            catch { }

            this.Close();
        }
    }
}
