<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>p7s.ico</ApplicationIcon>
    <AssemblyName>P7SViewer</AssemblyName>
    <RootNamespace>P7SViewer</RootNamespace>
    <!-- disable auto-generation of assembly attributes so we can control them in AssemblyInfo.cs -->
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="p7s.ico" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="p7s.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.5.1" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3856.49" />
    <PackageReference Include="SharpCompress" Version="0.38.0" />
    <PackageReference Include="System.Security.Cryptography.Pkcs" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="p7s.ico" />
  </ItemGroup>

</Project>
